### ISSUE TITLE
Save to EEPROM not persisting through reboot

### ISSUE THREAD

**Issue by robwolff3** [sijones/DiyBatteryBMS#5]
Hi again sijones, in trying to save my settings on the BMS page like you have in the wiki screenshot. I click "Save to EEPROM" but the values I set seem not persisting through reboot. After a reboot the BMS page values have reverted back to 0.

I see `Sending Save All command` in the web developer tools console. Is there any other logging or troubleshooting that can be done here?

**Comment by sijones** [comment]
There is a lot of output over the serial console, so if you monitor that at same time as the web console you should see what is happening.

Have you saved your wifi details and it's connecting to the wifi fine, it's just bms settings that aren't saving?

Check your serial console during start up, see if you see your values, i can't remember if i removed some of the logging here as it all seemed fine and wanted to reduce the amount of serial chat.

The contents of the textbox is sent to the esp when you leave the box, i.e. tab out, have a look at the console and see what the response is. The data sent between the web and esp is json over a websocket

It could be that the settings are saved just something isn't parsing for the web, open the dev console on connect to the esp and see the json response, is all the values in it right or are they 0 as well.
