### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by sibyseb** [sijones/DiyBatteryBMS#9]
Excellent work sijones. I just built this by flashing the zip file. The battery temperature is shown constantly as 10 degrees. In the picture the one wire sensor is to be connected to D22, but that pin is in use by CAN bus adapter. I may be missing something obvious, but would you be able to update me. Thank you in advance.
Siby

**Comment by sijones** [comment]
Thanks, there is no support for temperature at the moment, it is on the to do list but not there yet am afraid.

**Comment by sibyseb** [comment]
@sijones Thank you for the update.
